theme: null
include:
  - index.html
  - 404.html
exclude:
  - README.md
  - CLAUDE.md
  - CONTRIBUTING.md
  - CHANGELOG.md
  - "*.yml"
  - "*.json"
  - .github
  - node_modules
  - tests
  - docs
  - vitest.config.js
  - coverage
